// Embeds the compiled .wasm as a base64 JS module so the runtime needs no
// fetch/fs and Vite bundles it as plain JS. Run via `npm run build:wasm`.
import { readFileSync, writeFileSync } from 'node:fs';

const wasm = readFileSync(new URL('./anvil-unpack.wasm', import.meta.url));
const b64 = Buffer.from(wasm).toString('base64');
const out = `// AUTO-GENERATED by \`npm run build:wasm\` from wasm/anvil-unpack.ts — do not edit.\n`
  + `export const ANVIL_UNPACK_WASM_B64 = '${b64}';\n`;
writeFileSync(new URL('../src/content/maps/custom/anvil-unpack-wasm.js', import.meta.url), out);
console.log(`embedded ${wasm.length} wasm bytes -> ${b64.length} base64 chars`);
